dist: trusty
before_install:
  - sudo apt-get install -y ninja-build zip gawk
  # Arduino IDE adds a lot of noise caused by network traffic, trying to firewall it off
  - sudo iptables -P INPUT DROP
  - sudo iptables -P FORWARD DROP
  - sudo iptables -P OUTPUT ACCEPT
  - sudo iptables -A INPUT -i lo -j ACCEPT
  - sudo iptables -A OUTPUT -o lo -j ACCEPT
  - sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
script:
  - bash -x test.sh
  - cp Firmware/variants/1_75mm_MK25S-RAMBo13a-E3Dv6full.h Firmware/Configuration_prusa.h
  - bash -x build.sh || { echo "1_75mm_MK25S-RAMBo13a-E3Dv6full variant failed" && false; }
  - zip ./lang/MK25S-RAMBo13a.zip ./lang/*.hex
  - rm Firmware/Configuration_prusa.h
deploy:
  provider: releases
  api_key: $ACCESS_TOKEN
  file_glob: true
  file:
    - ./lang/*.zip
  skip_cleanup: true
  on:
    tags: true
